// <auto-generated />
namespace FinalProg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class crear_tabla_categorias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crear_tabla_categorias));
        
        string IMigrationMetadata.Id
        {
            get { return "202004071613490_crear_tabla_categorias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
